export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const ANALYSIS_PULL = 'ANALYSIS_PULL';
export const ANALYSIS_PULL_FAIL = 'ANALYSIS_PULL_FAIL';
export const INDIVIDUAL_ANALYSIS_PULL = 'INDIVIDUAL_ANALYSIS_PULL';
export const SPECIFIC_ANALYSIS_PULL = 'SPECIFIC_ANALYSIS_PULL';
export const EMPTY_STOCK_PAGE_ANALYSIS_PULL = 'EMPTY_STOCK_PAGE_ANALYSIS_PULL';

export const LOGOUT = 'LOGOUT';

export const SIGNUP = 'SIGN_UP';

export const USER_PROFILE_PUSH_START = 'USER_PROFILE_PUSH_START';
export const USER_PROFILE_PUSH_SUCCESS = 'USER_PROFILE_PUSH_SUCCESS';
export const USER_PROFILE_PUSH_FAIL = 'USER_PROFILE_PUSH_FAIL';

export const USER_PROFILE_PULL_START = 'USER_PROFILE_PULL_START';
export const USER_PROFILE_PULL_SUCCESS = 'USER_PROFILE_PULL_SUCCESS';
export const USER_PROFILE_PULL_FAIL = 'USER_PROFILE_PULL_FAIL';

export const CREATE_ANALYSIS_START = 'CREATE_ANALYSIS_START';
export const CREATE_ANALYSIS_SUCCESS = 'CREATE_ANALYSIS_SUCCESS';
export const CREATE_ANALYSIS_FAILURE = 'CREATE_ANALYSIS_FAILURE';

export const EDIT_ANALYSIS_START = 'EDIT_ANALYSIS_START';
export const EDIT_ANALYSIS_SUCCESS = 'EDIT_ANALYSIS_SUCCESS';
export const EDIT_ANALYSIS_FAILURE = 'EDIT_ANALYSIS_FAILURE';

export const COMMENT_PULL_START = 'COMMENT_PULL_START';
export const COMMENT_PULL_SUCCESS = 'COMMENT_PULL_SUCCESS';
export const COMMENT_PULL_FAILURE = 'COMMENT_PULL_FAILURE';

export const COMMENT_POST_START = 'COMMENT_POST_START';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE';
