# Generated by Django 3.0.7 on 2020-06-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200626_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.StockAnalysis'),
        ),
    ]
